### ISSUE TITLE
[BUG] Basic API does not work

### ISSUE THREAD

**Issue by lmyslinski** [ScriptSmith/instamancer#49] opened 2020-08-07 09:41 UTC
**Describe the bug**
Instamancer instantly goes to sleep when trying to use the api in non-full more. It finishes after a minute with no result.

![obraz](https://user-images.githubusercontent.com/5132069/89632732-f4b49b80-d8a2-11ea-9391-79e202ece3b0.png)

**To Reproduce**
`instamancer hashtag puppies`

Instamancer 3.3.1
Node 12.18.3
npm 6.14.4

I've tried this on multiple environments. The result is the same if I use the RegularAPI from javascript.

**Comment by ScriptSmith** [comment] 2021-01-04 08:39
Potential duplicate of #58

**Closed by ScriptSmith** 2021-01-04 08:39 UTC
Labels: bug
