### ISSUE TITLE
[BUG] - Symbol.asyncIterator is not defined.

### ISSUE THREAD

**Issue by jessqnnguyen** [ScriptSmith/instamancer#2] opened 2019-03-22 02:34 UTC
**Describe the bug**
I'm getting the following error when trying to run instamancer 

```
TypeError: Symbol.asyncIterator is not defined.
    at __asyncGenerator (/instamancer/src/api/instagram.js:4:38)
    at Hashtag.generator (/instamancer/src/api/instagram.js:145:16)
    at spawn (/instamancer/src/cli.js:238:41)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**To Reproduce**
I ran `instamancer hashtag instagood -d` after running through the installation steps on the README.

**Setup (please complete the following information):**
Node version - 6.9.0
Typescript version - 3.3.4000
Instamancer version - 1.3.1

**Comment by ScriptSmith** [comment] 2019-03-22 04:32
You'll need to use an up to date version of Node. v11 or v10 LTS should work.

**Comment by ScriptSmith** [comment] 2019-03-22 09:42
Duplicate of #1

**Closed by ScriptSmith** 2019-03-22 09:42 UTC
Labels: bug
